### PR TITLE
Fixed checkCfscriptEditorGrammar function throwing symbol.iterator error

### PR DESCRIPTION
**Pull request by David-Polehonski**
Excuse my editors liberal stripping of white space, fixing the issue with Atom v 1.19

### CODE REVIEW

**Comment by stoked74** [comment]
I started receiving this error last night after atom updated 1.19.0. I've updated my codebase with this pull request all is back to normal.

**Comment by seancorfield** [comment]
I'm not seeing an error directly, but no syntax highlighting is working for me with Atom 1.19 and opening CFML files seems to open them in tabs without getting focus. Is that likely the same problem?

**Comment by seancorfield** [comment]
Confirmed: updating that line and restarting Atom caused the problems to go away.

Can we get a new release a.s.a.p. with this PR merged @atuttle ?

**Comment by sean-codes** [comment]
This fixed me up! Ty!!!

**Comment by atuttle** [comment]
```
$ apm publish patch
Preparing and tagging a new version ✓
Pushing v0.17.1 tag ✓
Publishing language-cfml@v0.17.1 ✓
```

**Pull request merged**
