### PR TITLE
modified end for meta.function.cfml to support interfaces

### PR DESCRIPTION
**Pull request by zoo1**
Add grammer for #84 
test

### CODE REVIEW

**Comment by atuttle** [comment]
```
Preparing and tagging a new version ✓
Pushing v0.13.0 tag ✓
Publishing language-cfml@v0.13.0 ✓
```

Thanks for the contribution! @zoo1 would you like committer access, too?

**Comment by zoo1** [comment]
@atuttle that would be awesome!

**Comment by atuttle** [comment]
Sent you an invite. Just ping me any time you want a build pushed to apm.

**Comment by atuttle** [comment]
Strike that, looks like [anyone with a commit bit here on the repo can publish new package versions!](http://flight-manual.atom.io/behind-atom/sections/maintaining-your-packages/#adding-a-collaborator) All that I ask is that you follow [semver 2.0](http://semver.org/). 👍

**Comment by atuttle** [comment]
@elpete @seancoyne FYI, see my last comment. Glad I looked into this. 💃

**Pull request merged**
