### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by David-Polehonski**
Hello, I recently adopted us of atom for web development and found your language cfml package. I am keen to develop this project further and have done some refactoring and various updates to patterns and structure. You don't have to accept this pull request - but I will be continuing to develop this package for my own use.

### CODE REVIEW

**Comment by David-Polehonski** [comment]
I was trying to remove refences to 'Coldfusion' and replace them with 'cfml' the 'Coldfusion' references are left over from the textmate port. I changed the package name when I was unsure whether I would be able to contribute to the project (Needing permission from office). I have reverted it back to 'language-cfml'

**Comment by kliakos** [comment]
Do the above changes apply any improvements regarding the mixed cfml-html issues(highlight breaking)?  Or is it just refactoring?

**Comment by David-Polehonski** [comment]
I refactored the grammar into 3 grammars, an HTML(CFML) Mode, which highlights html with embedded cfml by deferring to atoms html grammar (which includes embedded js and css) This has seemingly resolved the highlighting issues for plain text content too. A CFML only grammar which ignores html and other languages but defers the content of cfscript blocks to the cfscript grammar which currenltly is achieving some reasonble support by emulating javascript however a proper grammar will be written in time.

**Comment by kliakos** [comment]
@atuttle yes, makes sense, didn't think of that.

**Comment by atuttle** [comment]
Thanks for your contributions, David. Get those little details above sorted out and I'll be happy to merge this into master and publish it. I'll also give you commit access to this repo so you don't have to use pull requests (unless you want to)...

**Comment by kliakos** [comment]
@David-Polehonski nice work! I have some serious problems with mixed html-cfml code breaking syntax highlight. Looking forward to see if your changes fix any of these issues.

**Comment by David-Polehonski** [comment]
@atuttle Will continue to work on it, commit access is useful for little tweaks but pull request give scope for greater feedback from users. @kliakos - thanks for the feedback it's always good to know when people are interested in project.

**Comment by David-Polehonski** [comment]
Ok, I've update the packge description and all .html references. Changing them to cfml gives hooks for styling cfml elements directly or more advanced plugin functionality later.

**Comment by atuttle** [comment]
Sorry to nit-pick! `Coldfusion` should be `ColdFusion`. :)

**Comment by David-Polehonski** [comment]
Amended character casing for ColdFusion & Railo in description.

**Comment by atuttle** [comment]
Sorry, one last thing then I promise I'm ready to merge and publish! The publish tool automatically increases the version number. You've changed it from `0.7.1` to `0.8.0`. When I publish it, I'll be sure to bump the minor number as you've done, but for now can you set it back to `0.7.1`? :)

**Comment by David-Polehonski** [comment]
I've set the minor number back. I didn't know the publish tool did that?

**Comment by atuttle** [comment]
Yeah, the command is something like `apm publish minor` (ala `npm version minor`) which increases the version number appropriately, commits that change, creates and pushes a tag, and then publishes it all to apm.

**Comment by atuttle** [comment]
```
$ apm publish minor                                                                                                               13:42  adam@retnadam
Preparing and tagging a new version ✓
Pushing v0.8.0 tag ✓
Publishing language-cfml@v0.8.0 ✓
```

**Pull request merged**
