### PR TITLE
Fix for issue #39

### PR DESCRIPTION
**Pull request by dajester2013**
use the api methods to attach the callbacks instead of working directly with the emitter.

also, some sanity checks in bindCfcChangeChecker

### CODE REVIEW

**Comment by dajester2013** [comment]
Changed the title to reference the correct issue number

**Comment by dajester2013** [comment]
I found a way to simplify and improve this even more... changes forthcoming.

**Comment by atuttle** [comment]
Let me know when you're ready for it to be merged.

**Comment by dajester2013** [comment]
ready to go

**Comment by atuttle** [comment]
#39

**Comment by atuttle** [comment]
```
$ apm publish patch
Preparing and tagging a new version ✓
Pushing v0.8.5 tag ✓
Publishing language-cfml@v0.8.5 ✓
```

**Pull request merged**
