### PR TITLE
fixes #14

### LINKED ISSUE #14: Deprecation Cop complaining after update to Atom v. 0.189.0
Screenshot:

atom-20150401

### PR DESCRIPTION
**Pull request by seancoyne**
Moves the settings from `scoped-properties` to `settings` as requested by the deprecation cop.

Hopefully someone who sees this in their Atom install (I'm on a Mac w/ Atom v0.189.0 and I don't see it) can test this and confirm that it stops Atom from complaining.

### CODE REVIEW

**Comment by seancoyne** [comment]
Can anyone confirm this fixes? If I don't get a response in a day or two I'm going to pull this in anyway.  We keep getting issues created because deprecation cop has a link to "create an issue".  Rather than deal with these duplicate issues, we can just pull in this fix.  Again, I don't see the deprecation warning on my system, so it would be best if one of you who sees it (@we3geeks, @Bendraneu, @mavelar) can confirm.

So, I'll give this another day or two, then pull it in if I don't hear anything.  We can merge it sooner if someone can confirm.

**Comment by Bendraneu** [comment]
Unfortunately it does not fix the issue:
bildschirmfoto 2015-04-13 um 14 46 29

**Comment by seancoyne** [comment]
It appears you're still running the older version, not the new branch.  Please try cloning from GH, switching to the bug-14 branch and using that.  You'll need to remove the old version from the .atom/packages directory (not sure where that is on Windows) and clone the new version there.

**Comment by Bendraneu** [comment]
Fix confirmed!

bildschirmfoto 2015-04-13 um 14 55 27

**Comment by seancoyne** [comment]
Great.  I'll merge now.  We will need to wait for @atuttle to push to apm though.

**Comment by atuttle** [comment]
Done! Thanks for the help guys.

**Pull request merged**
