### PR TITLE
Refactor to use @jqberquist Sublime Text 3 cfml port

### PR DESCRIPTION
**Pull request by elpete**
This fixes a lot of issues people are noticing in the package.  It also required a huge refactor of the tests.

Much thanks to @jcberquist for porting his awesome Sublime Text 3 package.

### CODE REVIEW

**Comment by elpete** [comment]
Strange....all the tests pass locally.

**Comment by elpete** [comment]
I've noticed too that Atom itself seems to sometimes pass all the tests and other times fail on seemingly random ones. ¯\_(ツ)_/¯

**Comment by elpete** [comment]
@atuttle I believe this will fix many of the issues people are complaining about.  It should be a better launching point to move forward than we're currently at.

**Comment by atuttle** [comment]
Should I push a new release, then?

**Comment by elpete** [comment]
I think so. 
Side note: I'm not using Atom as my daily driver anymore, so I'm not sure how much I'll be continuing to contribute after this one.

**Comment by atuttle** [comment]
Published as 0.12.0.

**Pull request merged**
