### PR TITLE
Fix for CGI scope tokenization

### PR DESCRIPTION
**Pull request by elpete**
Add CGI to list of scope matches

### CODE REVIEW

**Comment by atuttle** [comment]
Since you added the tests and I'm not up to speed with them yet, I'll just ask... Was there a failing test for this bug that's now passing? If Travis is reporting the individual test results, I haven't sniffed them out yet (granted, I've only skimmed them)...

**Comment by elpete** [comment]
Exactly.  This fixed adding the CGI scope to the list of scope types.

**Comment by atuttle** [comment]
Yeah the change seems small and simple enough... I just don't see a test for it. Whatevs! I'll just go ahead and merge it. :)

**Comment by atuttle** [comment]
```
$ apm publish minor
Preparing and tagging a new version ✓
Pushing v0.10.0 tag ✓
Publishing language-cfml@v0.10.0 ✓
```

**Pull request merged**
